apiVersion: v1
kind: Service
metadata:
  name: kafka-cluster
  namespace: {{ .Values.namespace }}
  labels:
    app: kafka
spec:
  ports:
  - port: 9092
    name: client
  selector:
    app: kafka
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-cluster
  namespace: {{ .Values.namespace }}
  labels:
    app: kafka
spec:
  replicas: {{ .Values.kafka.replicasCount }}
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: {{ .Values.kafka.image.repository }}
        resources:
          limits:
            memory: 1Gi
          requests:
            memory: 1Gi
            cpu: 1
        # readinessProbe:
        #   httpGet:
        #     path: /private/ready
        #     port: 8080
        #   initialDelaySeconds: 15
        #   timeoutSeconds: 1
        # livenessProbe:
        #   httpGet:
        #     path: /private/status
        #     port: 8080
        #   initialDelaySeconds: 30
        #   timeoutSeconds: 1
        ports:
        - name: http
          containerPort: 9092
          protocol: TCP
        volumeMounts:
        - name: kafka-certs-config
          mountPath: /server-certs
          readOnly: false
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper.{{ .Values.namespace }}:2181"
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_LISTENERS
          value: "INTERNAL://:9093,EXTERNAL://:9092"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "INTERNAL://localhost:9093,EXTERNAL://kafka-cluster.{{ .Values.namespace }}:9092"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "INTERNAL:PLAINTEXT,EXTERNAL:SSL"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "INTERNAL"
        #----- SSL --------#
        - name: KAFKA_SSL_KEYSTORE_LOCATION
          value: "/server-certs/server.keystore.jks"
        - name: KAFKA_SSL_KEYSTORE_PASSWORD
          value: "password"
        - name: KAFKA_SSL_KEY_PASSWORD
          value: "password"
        - name: KAFKA_SSL_TRUSTSTORE_LOCATION
          value: "/server-certs/server.truststore.jks"
        - name: KAFKA_SSL_TRUSTSTORE_PASSWORD
          value: "password"
        - name: KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM
          value: ""
        - name: KAFKA_SSL_CLIENT_AUTH
          value: "requested"
      volumes:
      - name: kafka-certs-config
        secret:
          secretName: kafka-server-certs
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30