version: '3.9'

services:
  zoo1:
    image: zookeeper
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
  zoo2:
    image: zookeeper
    depends_on:
      - zoo1
    hostname: zoo2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zoo3:2888:3888;2181
  zoo3:
    image: zookeeper
    depends_on:
      - zoo2
    hostname: zoo3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181

  kafka1:
    image: wurstmeister/kafka:latest
    hostname: kafka1
    ports:
      - 9094:9094
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zoo1:2181,zoo2:2181,zoo3:2181
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=INTERNAL://kafka1:9092,INTERNAL_SECURE://kafka1:9093,EXTERNAL://kafka1:9094
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka1:9092,INTERNAL_SECURE://kafka1:9093,EXTERNAL://localhost:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,INTERNAL_SECURE:SSL,EXTERNAL:SSL
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      #----- SSL --------#
      - KAFKA_SSL_KEYSTORE_LOCATION=/server-certs/server.keystore.jks
      - KAFKA_SSL_KEYSTORE_PASSWORD=password
      - KAFKA_SSL_TRUSTSTORE_LOCATION=/server-certs/server.truststore.jks
      - KAFKA_SSL_TRUSTSTORE_PASSWORD=password
      - KAFKA_SSL_KEY_PASSWORD=password
      - KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=''
      - KAFKA_SSL_CLIENT_AUTH=required
    volumes:
      - ./kafka-volumes/kafka1/data:/var/lib/kafka/data
      - ./kafka/server-certs:/server-certs/
  kafka2:
    image: wurstmeister/kafka:latest
    hostname: kafka2
    ports:
      - 9095:9095
    depends_on:
      - zoo1
      - zoo2
      - zoo3
      - kafka1
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zoo1:2181,zoo2:2181,zoo3:2181
      - KAFKA_BROKER_ID=2
      - KAFKA_LISTENERS=INTERNAL://kafka2:9092,INTERNAL_SECURE://kafka2:9093,EXTERNAL://kafka2:9095
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka2:9092,INTERNAL_SECURE://kafka2:9093,EXTERNAL://localhost:9095
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,INTERNAL_SECURE:SSL,EXTERNAL:SSL
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL #internal_secure doesnt work with these certificats? mayb the cert names?
      #----- SSL --------#
      - KAFKA_SSL_KEYSTORE_LOCATION=/server-certs/server.keystore.jks
      - KAFKA_SSL_KEYSTORE_PASSWORD=password
      - KAFKA_SSL_TRUSTSTORE_LOCATION=/server-certs/server.truststore.jks
      - KAFKA_SSL_TRUSTSTORE_PASSWORD=password
      - KAFKA_SSL_KEY_PASSWORD=password
      - KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=''
      - KAFKA_SSL_CLIENT_AUTH=required
    volumes:
      - ./kafka-volumes/kafka2/data:/var/lib/kafka/data
      - ./kafka/server-certs:/server-certs/

  kafka-producer:
    build: .
    environment:
      - DEPLOYMENT_ENVIRONMENT=docker-compose
      - KAFKA_BOOTSTRAP_SERVERS=kafka1:9093,kafka2:9093
    ports:
      - "8080:8080"
    depends_on:
      - kafka1
      - kafka2
    volumes:
      - ./kafka/client-certs:/client-certs/
