apiVersion: v1
kind: Namespace
metadata:
  name: kafka-cluster-dev
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
  namespace: kafka-cluster-dev
spec:
  hard:
    limits.memory: 3Gi
    pods: "10"
    requests.cpu: "8"
    requests.memory: 3Gi
    requests.storage: "0"
    resourcequotas: "1"
