apiVersion: v1
kind: Namespace
metadata:
  name: kafka-cluster-dev
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
---
apiVersion: v1
items:
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: quota
    namespace: kafka-cluster-dev
  spec:
    hard:
      limits.memory: 2Gi
      pods: "10"
      requests.cpu: "8"
      requests.memory: 2Gi
      requests.storage: "0"
      resourcequotas: "1"
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""